module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts', 'tsx'],
  rootDir: 'src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)sx?$': 'ts-jest',
  },
  collectCoverageFrom: [
    '**/*.(t|j)s',
    '!**/*.d.ts',
    '!**/*.module.ts',
    '!**/*.schema.ts',
    '!**/*.controller.ts',
    '!main.ts',
    '!**/*.interface.ts',
    '!**/*.dto.ts',
    '!**/*.enum.ts',
    '!**/*.type.ts',
    '!swagger/**',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/$1',
    '^src/(.*)$': '<rootDir>/$1',
    '\\.(tsx)$': '<rootDir>/../test/mocks/fileMock.js',
  },
  setupFilesAfterEnv: ['<rootDir>/../test/setup.ts'],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '/dist/',
    '.module.ts$',
    '.schema.ts$',
    '.controller.ts$',
    'main.ts$',
  ],
  testTimeout: 30000,
  verbose: true,
};
