export const FILES_REPOSITORY = Symbol('FILES_REPOSITORY');
export const FOLDERS_REPOSITORY = Symbol('FOLDERS_REPOSITORY');
export const STATS_REPOSITORY = Symbol('STATS_REPOSITORY');
export const USERS_REPOSITORY = Symbol('USERS_REPOSITORY');
export const TOKENS_REPOSITORY = Symbol('TOKENS_REPOSITORY');
export const DATABASE_CONNECTION = Symbol('DATABASE_CONNECTION');
